name: Siarhei doc errors checker
description: Inspects documentation for errors
branding:
  icon: corner-down-right
  color: purple

inputs:
  instance:
    description: 'The instance or group variable (format: "Writerside/instanceID" or "Writerside/groupID")'
    required: true
  is-group:
    description: 'Set to any value to treat the instance as a group'
    required: false
    default: ''

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - 'artifacts/report.json'
    - '${{ inputs.instance }}'
    - '${{ inputs.is-group }}'
